### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by devgianlu** [lindell/github-release-cli#4]
### Configuration

```
before_deploy:
  - curl https://github.com/lindell/github-release-cli/releases/download/1.3.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
  - export BODY=$(cat app/src/main/play/release-notes/en-GB/production.txt)
  - export RELEASE_NAME="Release $(./gradlew -q :app:printVersionName)"
  - export FILES=app/build/outputs/apk/foss/release/*

deploy:
  - provider: script
    script: ./github-releaser -draft -verbose
    skip_cleanup: true
    on:
      repo: devgianlu/DNSHero
      branch: master
      tags: true
```

### Error message
    2019/08/09 12:42:00 Post https://uploads.github.com/repos/devgianlu/DNSHero/releases/0/assets?label=app-foss-release.apk&name=app-foss-release.apk: EOF

https://travis-ci.com/devgianlu/DNSHero/builds/122584069
